### PR TITLE
xmlsec-mscrypto/mscng: fix leaks in *StoreAdoptCert, fix CERT_CONTEXT leaks

### PR DESCRIPTION
**Pull request by postboy**
Make behavior consistent with similar functions *AdoptCert and *AdoptCrl and with high-level calls from two instances of app.c.

Similar to https://github.com/lsh123/xmlsec/pull/641.

Part of https://github.com/lsh123/xmlsec/issues/638.

### CODE REVIEW

**Comment by postboy** [comment]
Second commit could be a separate pull request if you want. My bad, I accidentally commited to the same branch twice!

**Comment by postboy** [comment]
Seems that I understood your idea and fixed the problem that you pointed to!

**Comment by lsh123** [comment]
Thanks, looks good -- I will merge it as soon as CI completes

**Comment by lsh123** [comment]
thank you!

**Pull request merged**
