### PR TITLE
Remove unused iconv build options

### PR DESCRIPTION
**Pull request by metsma**
Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by metsma** [comment]
Least I don't see any usage in code or it needs to be documented how it is used.

**Comment by lsh123** [comment]
iconv is a dependency for libxml2

**Comment by lsh123** [comment]
linking is required because it will not build otherwise. I agree include is not required but I don't care much about it.

**Comment by metsma** [comment]
Strange I just tested and it did not require iconv lib. Did you link with libxml2 statically?

**Comment by lsh123** [comment]
I don't really use windows :)

**Comment by metsma** [comment]
We can help out with this. We need to support all platforms (win, mac, linux, ios, android).
Can the default option then be disabled.
Least all github action/readme/bat files force option to "iconv=no"

**Comment by lsh123** [comment]
Not sure why you can't just pass `iconv=no` for configure.js options to disable it.

Said that, I agree that iconv=no should be default (I believe building iconv on windows is still non-trivial). See PR #834

**Comment by metsma** [comment]
I can pass iconv=no. I was just under impression why it is needed.
There is no mention iconv in autoconf build system.
Also readme does not mention that it enables or disables any feature.
It builds just fine without it and all build (even github actions) references specify iconv=no.
Therefore I thought it is some old cruft and can safely be removed and avoid any unexpected surprises.

**Pull request closed without merging**
